### ISSUE TITLE
[bug] milvus cluster crashes and quits automatically

### ISSUE THREAD

**Issue by jingkl** [milvus-io/milvus-helm#310]
bitnami etcd a known issue, did not save member_id to file properly
![20220309-184237](https://user-images.githubusercontent.com/34296482/157426080-7d74cd27-3b3c-4a60-9d4e-981864ed795f.png)

benchmark-57sbh（client-configmap:client-random-locust-100m-ddl-r8-w2,server-configmap:server-cluster-8c64m)

```
ode016.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-minio-3                                1/1     Running            0          30m    10.97.19.243   qa-n
ode016.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-autorecovery-5ffd4d8b7b-l2bnl   1/1     Running            0          30m    10.97.19.234   qa-n
ode016.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-bastion-59596bb854-rsk42        1/1     Running            0          30m    10.97.18.51    qa-n
ode017.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-bookkeeper-0                    1/1     Running            0          30m    10.97.19.237   qa-n
ode016.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-bookkeeper-1                    1/1     Running            0          28m    10.97.16.188   qa-n
ode013.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-bookkeeper-2                    1/1     Running            0          28m    10.97.16.202   qa-n
ode013.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-broker-bf65bdd5b-z5g5t          1/1     Running            0          30m    10.97.10.76    qa-n
ode008.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-proxy-64b9dc478b-ksc2n          2/2     Running            0          30m    10.97.5.19     qa-n
ode003.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-zookeeper-0                     1/1     Running            0          30m    10.97.18.52    qa-n
ode017.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-zookeeper-1                     1/1     Running            0          30m    10.97.18.53    qa-n
ode017.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-zookeeper-2                     1/1     Running            0          29m    10.97.10.77    qa-n
ode008.zilliz.local   <none>           <none>
benchmark-57sbh-2245676010: benchmark-57sbh-1-pulsar-zookeeper-metadata-r4ldl        0/1     Completed          0          30m    10.97.18.50    qa-n
ode017.zilliz.local   <none>           <none>
```

**Comment by LoveEachDay** [comment]
This is a know issue for bitnami/etcd chart, which fails to save the member_id into a file occasionally.

/assign

**Comment by saisona** [comment]
I get the same issue here in standalone mode

**Comment by haorenfsa** [comment]
bitnami/bitnami-docker-etcd#42

**Comment by dhanangw** [comment]
The etcd issue has been fixed in this PR:
https://github.com/bitnami/bitnami-docker-etcd/pull/44 

May I upgrade the etcd version in [values.yaml](https://github.com/milvus-io/milvus-helm/blob/106d58a725a97c10c4ff35186c8283fdd998aadb/charts/milvus/values.yaml#L413) to the newest version?

**Comment by haorenfsa** [comment]
> bitnami/bitnami-docker-etcd#44

Hi, the fix is actually in bitnami/bitnami-docker-etcd#42, but the official version still has some issue if you upgrade from a quite old version, like what milvus v2.0.2 is using. We're testing our patches about this upgrade and we'll soon have an stable version for upgrade.

**Comment by haorenfsa** [comment]
And by the way the patch bitnami/bitnami-docker-etcd#44 is not merged yet, so `Cluster ID mismatch` issue will still exists in current official image. We're going to the etcd image in our own repo to speed up the patch merging procedure. see https://github.com/milvus-io/bitnami-docker-etcd.

If you really want to upgrade etcd now, you can try using the image `milvusdb/etcd:3.5.0-r4`. But it's still under testing, for now it looks good, but still you need to be careful.

**Comment by haorenfsa** [comment]
bitnami/bitnami-docker-etcd#46

**Comment by deshetti** [comment]
Looks like the PR https://github.com/milvus-io/milvus-helm/pull/343 didn't fix the issue.

I have upgraded to the latest chart and the issue still persists. Our Production system is down with this issue. Any help is appreciated. Thanks.

**Comment by haorenfsa** [comment]
> Looks like the PR #343 didn't fix the issue.
> 
> I have upgraded to the latest chart and the issue still persists. Our Production system is down with this issue. Any help is appreciated. Thanks.

Could you plz provide how your etcd pod states & logs, as well as how you did the upgrade?
It's quite well tested by our QA team. I also tested it dozens of times.

**Comment by haorenfsa** [comment]
The key is  pay attention to your etcd image, is it `bitnami/etcd:3.5.0-debian-10-r24` or `milvusdb/etcd:3.5.0-r6`.
The latter one is what this patch provided. If your etcd is not using it, maybe you didn't upgrade it correctly

**Comment by deshetti** [comment]
> 

@haorenfsa sorry for the delayed response. I made sure that the correct etc image was used as you mentioned. I have gone through a few other etcd issues linked where this was discussed as well, so I understood what the issue was at a high level. I am not able to send you the logs at the moment as we upgraded to the latest version of the Milvus helm chart and etcd helm version.

This was a production system and we could not leave it down for a long time. I moved it to the latest helm chart version as of 10 days ago and used the latest etcd helm chart at that time. We reindexed the database once again and so far things seem to work fine. I tried to bring down a node in the cluster and restarted the entire etcd cluster and things seem to work fine.

**Comment by haorenfsa** [comment]
> This was a production system and we could not leave it down for a long time. I moved it to the latest helm chart version as of 10 days ago and used the latest etcd helm chart at that time. We reindexed the database once again and so far things seem to work fine. I tried to bring down a node in the cluster and restarted the entire etcd cluster and things seem to work fine.

According to your description, it seems to me that the etcd still run fine after upgrade while Milvus had some index problems?  So you just reindexed and didn't do anything else to recover it right?

**Comment by deshetti** [comment]
Nope, etcd cluster was failing to restart with the following errors and for that reason, rest of the Milvus was unable to start:

```
4
{"level":"warn","ts":"2022-07-13T20:47:11.715Z","caller":"rafthttp/http.go:413","msg":"failed to find remote peer in cluster","local-member-id":"519b58c5147dba54","remote-peer-id-stream-handler":"519b58c5147dba54","remote-peer-id-from":"96dab2a30f2d0751","cluster-id":"3c51e6e041592dc4"}
3
{"level":"warn","ts":"2022-07-13T20:47:11.715Z","caller":"rafthttp/http.go:413","msg":"failed to find remote peer in cluster","local-member-id":"519b58c5147dba54","remote-peer-id-stream-handler":"519b58c5147dba54","remote-peer-id-from":"96dab2a30f2d0751","cluster-id":"3c51e6e041592dc4"}
2
{"level":"info","ts":"2022-07-13T20:47:11.719Z","caller":"etcdmain/main.go:47","msg":"notifying init daemon"}
1
{"level":"info","ts":"2022-07-13T20:47:11.719Z","caller":"etcdmain/main.go:53","msg":"successfully notified init daemon"}
```

<img width="558" alt="Screen Shot 2022-07-26 at 4 00 16 PM" src="https://user-images.githubusercontent.com/10763210/181111275-a8cc98d3-0f2b-4e32-8958-f6c83d291170.png">

I had to reinstall Milvus with the new helm chart and latest version of etcd and reindex for our production site to work as expected.

**Comment by haorenfsa** [comment]
> I had to reinstall Milvus with the new helm chart and latest version of etcd and reindex for our production site to work as expected.

Could you provide the commands you executed in these upgrades?  I got a little  confused.

First you `have upgraded to the latest chart and the issue still persists.` And  `Production system is down with this issue.`

And how you fix this is through `reinstall Milvus with the new helm chart and latest version of etcd and reindex`

So by `reinstall` do you mean `helm uninstall` & `helm install` again?  
And is the `the new helm chart and latest version of etcd` same as the `latest chart` you upgraded to in the first place?

**Comment by deshetti** [comment]
> So by reinstall do you mean helm uninstall & helm install again?

Yes.

> And is the the new helm chart and latest version of etcd same as the latest chart you upgraded to in the first place?

I used the latest etcd helm chart from bitnami
